version: '3.8'

services:

  dbnuponto:
    image: postgres:latest
    container_name: dbnuponto
    environment:
      POSTGRES_DB: dbnuponto
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbnuponto-data:/var/lib/postgresql/data 
    networks:
      - my-networks  
    restart: always  

  pgadminnuponto:
    image: dpage/pgadmin4
    container_name: pgadminnuponto
    environment:
      PGADMIN_DEFAULT_EMAIL: nuponto@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres 

    ports:
      - "15432:80"  
    networks:
      - my-networks 
    restart: always

  nuponto-app:
    build:
      context: ./nuponto
      dockerfile: dockerfile
    container_name: nuponto-app
    ports:
      - "8080:8081"  
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbnuponto:5432/dbnuponto 
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres 
    networks:
      - my-networks 
    depends_on:
      - dbnuponto
    restart: always

  servico-localizacao:
    build:
      context: ./servicolocalizacao
      dockerfile: dockerfile
    container_name: servico-localizacao
    ports:
      - "3000:3000"
    restart: always

networks:
  my-networks:
    driver: bridge 

volumes:
  dbnuponto-data: 