# Etapa 1: Compilação do projeto com Maven
FROM maven:3.9.6-eclipse-temurin-21 AS build

WORKDIR /app

# Copia o pom.xml e baixa as dependências
COPY pom.xml .

# Copia o restante do código-fonte
COPY . .

# Compila o projeto e gera o .jar
RUN mvn clean package -DskipTests

# Etapa 2: Imagem final mais enxuta para rodar o .jar
FROM eclipse-temurin:21

WORKDIR /opt/app

# Copia apenas o .jar gerado da etapa anterior
COPY --from=build /app/target/*.jar app.jar

# Comando para iniciar a aplicação
CMD ["java", "-jar", "app.jar"]
